### ISSUE TITLE
SP4: long press causes crash

### ISSUE THREAD

**Issue by ryivhnn** [AkashaProject/Alpha#100]
I have long press right click disabled and managed to make the client crash by "long pressing" on any of the posts both in stream view and post view.  The first long press was accidental as I just stopped scrolling but kept holding on to the screen and not really paying attention to how I was holding it, the following three times I did for testing purposes resulted in the crash every time.

I'm too scared to test with long press right click enabled as I disabled it as one of many things in an epic quest to get my Cintiq working with the Surface Pro and I need the Cintiq to work :)

**Comment by 42piratas** [comment]
Hey @ryivhnn 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
