### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by konfou** [AkashaProject/Alpha#102]
I'm getting the following warnings running akasha on terminal:
```
(node:5107) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by 42piratas** [comment]
Hey @konfou 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
