### ISSUE TITLE
nothing worked / restart / fine

### ISSUE THREAD

**Issue by konfou** [AkashaProject/Alpha#103]
It is the same as #88 but on Arch Linux.
Nothing was working besides loading the stream. 
I restarted and everything is fine.
I'm attaching APP and ipfs error logs.

[APP.error.log.txt](https://github.com/AkashaProject/Alpha/files/960993/APP.error.log.txt)
[ipfs.error.log.txt](https://github.com/AkashaProject/Alpha/files/960996/ipfs.error.log.txt)

**Comment by 42piratas** [comment]
Hey @konfou!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
