### ISSUE TITLE
Licensing not saved as default

### ISSUE THREAD

**Issue by boozook** [AkashaProject/Alpha#104]
#### Steps to reproduce 

When publishing a post:

1. select `Licence`
1. in the `Licensing`:
    1.  select any option (e.g. `Public Domain`)
    1.  select any `Set as default license`
    1.  `Done`
1. publish the post
1. create new post and its license will be not a `Public Domain`

![screen shot 2017-05-06 at 15 14 07](https://cloud.githubusercontent.com/assets/888526/25772212/c0b5e542-326e-11e7-99a2-ec0cae3990f3.png)

**Comment by 42piratas** [comment]
Hey @fzzr- 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
