### ISSUE TITLE
endless synchronizing on Mac

### ISSUE THREAD

**Issue by Mattshiva** [AkashaProject/Alpha#105]
2.8 GHz Intel Core 7
4GB 10067 MHz DDR3

Synchronizing goes on and on and on day in day out

**Comment by 42piratas** [comment]
Hey @Mattshiva 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
