### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by ghost** [AkashaProject/Alpha#106]
I can't begin syncing the blockchain. I immediately get the error:
`SGE01Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use`

Running MacOS 10.12.4. Akasha client v0.5.2.

**Comment by zinaidac** [comment]
How Could we solve this ?

Zinaida Anastasiu

**Comment by 42piratas** [comment]
Hey @imvunoah and @zinaidac 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
