### ISSUE TITLE
Unable to Register Identity

### ISSUE THREAD

**Issue by saarthakpuri** [AkashaProject/Alpha#108]
Mac Book Air running OSX El Capitan
4 GB 1600 MHz DDR3

Identity Registration step gets stuck at "Creating Local Ethereum Key" and does not proceed from there. 
Screenshot attached. 

![screenshot](https://cloud.githubusercontent.com/assets/17100868/26715423/50fd7dac-4793-11e7-9ae9-e2d7ce0fdb4c.png)

**Comment by amarjeet000** [comment]
+1

**Comment by 42piratas** [comment]
Hey @saarthakpuri and @amarjeet000 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
