### ISSUE TITLE
Getting could not open database

### ISSUE THREAD

**Issue by stauntonknight** [AkashaProject/Alpha#113]
Fatal: Could not open database: resource temporarily unavailable
even running the command line shown in the logs show the same error.

Stacktrace : 
SGE01I0613 17:21:24.189290 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to 
SGE01geth: exited with code: 1
SGE01geth connection timeout

**Comment by 42piratas** [comment]
hey @stauntonknight 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you're still facing the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
