### ISSUE TITLE
Adding new draft is prefilled with un-published other draft

### ISSUE THREAD

**Issue by nextlevelshit** [AkashaProject/Alpha#115]
`OS: Ubuntu Gnome 17.04`
Clicking on "NEW ENTRY" inside the overview of my entries opens new window, which is prefilled with content of another un-published draft of mine.

**Comment by 42piratas** [comment]
Hey @nextlevelshit!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
