### ISSUE TITLE
Several issues on OSX

### ISSUE THREAD

**Issue by moodledidoodledi** [AkashaProject/Alpha#12]
Hi Guys!

After using AKASHA for 3 days now on OSX, I encountered several small issues that I wanted to report:

1. The "add photo button" works 70% of the time, but sometimes I press enter and he doesn't appear or he is stuck somewhere in the article that I write and is not moving.

2. If you mark text, the option box for bold/italic doesn't always appear. If it does ad you klick somewhere, in 90% of all tries nothing happens and the text doesn't get bold. At some point after some clicking AKASHA didn't respond anymore and suddenly half of my article was gone and couldn't be retrieved through cmd + z (an amazing feature that works perfectly btw).

3. When trying to add a tag AKASHA often lags for some seconds, especially when you accidentally try to start the new Tag with a capital letter

4. I once wanted to publish a comment and after I agreed to spend the gas nothing happened except a blue circle moving all the time. After some time I restarted the app and published the comment again, this time the "enter your PW" field popped up. Weirdly, although I didn't enter my password the first try, BOTH comments got published.

5. klicking on the symbol behind the links in the profile doesn't work. An animation shows up but nothing happens

6. When downloading from GitHub the OSX version doesn't install ipfs and geth automatically (at least for me that was the case)

**Comment by 42piratas** [comment]
First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you're still facing the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
