### ISSUE TITLE
Won't sync

### ISSUE THREAD

**Issue by rodsevern** [AkashaProject/Alpha#126]
I am keen to load Akasha but cannot move past the following errors.  

SIE01Cannot start IPFS service. Check logs for more details. 
SGE01geth connection timeout 

Appreciate any assistance. 
Rod.

**Comment by PuppeteerQ** [comment]
I have the same problem.

**Comment by 42piratas** [comment]
Hey @rodsevern and @PuppeteerQ!

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
