### ISSUE TITLE
My AKASHA won't run

### ISSUE THREAD

**Issue by PuppeteerQ** [AkashaProject/Alpha#130]
Hi,

Here is some background info:

What I downloaded: AKASHA exe file
My OS: Win10

Issue: When I was choosing avatar picture from my desktop it stopped to respond; so I right clicked to close the window. However the next time I opened AKASHA it said 

>  Synchronization was stopped
> Your machine is currently synchronizing with the Ethereum world computer network. You will be able to log in and enjoy the full AKASHA experience as soon as the sync is complete.

  Resume doesn't work as well. Basically what happened is I exited before the synchronization was completed. Is there any ways that I can leave Ethereum network or restart?

**Comment by 42piratas** [comment]
Hey @PuppeteerQ 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the `/dapp` repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
