### ISSUE TITLE
SGE01geth: exited with code: 1 SGE01geth connection timeout SGE01geth connection timeout SIE01Cannot start IPFS service. Check logs for more details.

### ISSUE THREAD

**Issue by canopussy** [AkashaProject/Alpha#131]
SGE01geth: exited with code: 1
SGE01geth connection timeout
SGE01geth connection timeout
SIE01Cannot start IPFS service. Check logs for more details.

**Comment by 42piratas** [comment]
Hey @canopussy!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
