### ISSUE TITLE
app doesnt open on mac

### ISSUE THREAD

**Issue by yoni9091** [AkashaProject/Alpha#136]
mac doesnt allow me to open an an "familiar apps" what should i do?

yonatan

**Comment by 42piratas** [comment]
Hey @yoni9091 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the `/dapp` repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
