### ISSUE TITLE
Screen goes white when editing image caption text

### ISSUE THREAD

**Issue by mdotstrange** [AkashaProject/Alpha#139]
Using latest beta on Windows- when I click on the caption field of an image in a draft the whole UI goes white- I was able to get back to the draft by using the "Reload" command under the "View" menu- repeated the bug three times in a draft-

Link to screen cap of whited out UI https://i.imgur.com/5o50Jcu.png

// Amazing job on the beta- its light years better then the alpha.

**Comment by 42piratas** [comment]
Hey @mdotstrange 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
