### ISSUE TITLE
Error when forging AETH

### ISSUE THREAD

**Issue by maxizrin** [AkashaProject/Alpha#141]
I get the following error when forging AETH:

"Error code PTEE02
An error occurred while transforming 1000 Essence"

ETH was still deducted for the operation.

EDIT: it did work with 2000 essence.

**Comment by 42piratas** [comment]
Hey @maxizrin! 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
