### ISSUE TITLE
Open the AKASHA dapp and synchronize with the network

### ISSUE THREAD

**Issue by vovo999** [AkashaProject/Alpha#142]
How much time synchronization required？

**Comment by 42piratas** [comment]
Hey @vovo999!

First, I'm sorry for the late reply. 

The synchronization time varies a lot according to each person's Internet connection speed, and unfortunately it might take even several hours, because you're synchronizing an entire Ethereum node.

BUT you can try the AKASHA web, which doesn't require such synchronization:
https://beta.akasha.world

If you have any other question, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

Cheers! :pray::metal:
