### ISSUE TITLE
Can't see dialog box to post

### ISSUE THREAD

**Issue by clarkjdj** [AkashaProject/Alpha#143]
Hi, I'm trying to post an entry and I get a blank dialog box that I can't get past.  It was working fine yesterday.

Let me know how I can help troubleshoot.

<img width="1143" alt="screen shot 2018-01-22 at 10 21 59 am" src="https://user-images.githubusercontent.com/11020834/35228210-269ded3e-ff5e-11e7-990d-9ba65feb328a.png">

**Comment by bogdanbrezuica** [comment]
hello @clarkjdj . This is a known issue in Akasha 0.6.1 that will be fixed in 0.6.2. This is happening when you manafy all your AETH, so the easiest work-around is to transfer some AETH to your wallet (either from another account of yours if you have more than 1, or you can send your public address here and we can send you some AETH). You can see your public address when you open ETH or AETH wallet from the upper right corner.

Also, please use the ["dapp" repo](https://github.com/AkashaProject/dapp) for issues related to the beta version, this one was used for the alpha (we need to update the link from the "help" menu in the app)

**Comment by clarkjdj** [comment]
Great, thanks

**Comment by clarkjdj** [comment]
If you could send me a small amount of AETH, you are right -- I manafied all of mine.

0xe6ef3d1ee39520da45fbda959511d83607b2ec47

Cheers,

**Comment by bogdanbrezuica** [comment]
done
