### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by HenryHMZ** [AkashaProject/Alpha#144]
I downloaded and run on my desktop under Win7 x64, after Synchronization completed, nothing hapen.
Just stoped there. What ever run as full or light sync. Please guide me how to fix the problem.

**Comment by 42piratas** [comment]
Hey @HenryHMZ 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the repo [/dapp](https://github.com/AkashaProject/dapp) and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
