### ISSUE TITLE
Synchronization was stopped

### ISSUE THREAD

**Issue by lindsaysmella** [AkashaProject/Alpha#146]
Anytime I try and start the application I just get the message, "Synchronization was stopped"
restarted computer and everything but still just getting the Synchronization was stopped message.

I didn't change anything other than its been a few day since I started the application and had logged in.

**Comment by 42piratas** [comment]
Hey @lindsaysmella 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
