### ISSUE TITLE
Stuck on loading draft

### ISSUE THREAD

**Issue by mobiledevgroup** [AkashaProject/Alpha#148]
No responding and very slow to load dashboard entries

**Comment by 42piratas** [comment]
Hey @mobiledevgroup 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the `Alpha` version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
