### ISSUE TITLE
Error code DPE01 when I try to publish a link

### ISSUE THREAD

**Issue by mobiledevgroup** [AkashaProject/Alpha#149]

**Comment by 42piratas** [comment]
Hey again @mobiledevgroup! 

Same, same: I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap. 

Cheers!
