### ISSUE TITLE
I can’t get over the IPFS service in the welcome screen. AKASHA synchronises with Ethereum but IPFS can’t start, so I’m blocked

### ISSUE THREAD

**Issue by kayaniha** [AkashaProject/Alpha#150]
I can’t get over the IPFS service in the welcome screen. AKASHA synchronises with Ethereum but IPFS can’t start, so I’m blocked. I can't use AKASKA and screening keep searching peers but still not complete.

**Comment by 42piratas** [comment]
Hey @kayaniha 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
