### ISSUE TITLE
AKASHA synchronizes not finish

### ISSUE THREAD

**Issue by kayaniha** [AkashaProject/Alpha#151]
I can’t get over the IPFS service in the welcome screen. AKASHA synchronises with Ethereum but IPFS can’t start, so I’m blocked.

**Comment by 42piratas** [comment]
Hey @kayaniha 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!

**Comment by kayaniha** [comment]
hi,

please send me beta version so i can register there

thanks

**Comment by kenshyx** [comment]
You can check the beta web version at https://beta.akasha.world
