### ISSUE TITLE
Syncing for 2 days now

### ISSUE THREAD

**Issue by BLACKX714** [AkashaProject/Alpha#153]
Your machine is currently synchronizing with the Ethereum world computer network. You will be able to log in and enjoy the full AKASHA experience as soon as the sync is complete. Still trying to find peers. Under view details it said "clock not in sync may cause issue" I re-synced my clock and still not connecting to peers.

**Comment by 42piratas** [comment]
Hey @BLACKX714 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
