### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by BLACKX714** [AkashaProject/Alpha#154]
It's been weeks now and still syncing, What do I do?

**Comment by 42piratas** [comment]
Hey again @BLACKX714 

Same, same of before: I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you're still facing the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

Cheers! :pray::metal:
