### ISSUE TITLE
Test ether request keep spinning

### ISSUE THREAD

**Issue by cpekiner** [AkashaProject/Alpha#158]
Trying to create a new article but it says no ether to publish an article and provides the option to get some test ether but clicking the button to get some test ether keeps spinning and it stays there for hours.

**Comment by c0smas** [comment]
same thing. can't even create a profile. It says "You don`t have enough test ETH. Please request some by clicking the button below!" I pushing this button very hard but it just keeps spinning.

**Comment by 42piratas** [comment]
Hey again @cpekiner 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
