### ISSUE TITLE
akasha beta stuck

### ISSUE THREAD

**Issue by busernya** [AkashaProject/Alpha#159]
it says in the details:  'please enable network time synchronisation in system settings' and it keeps repeating this,pls advice 
kind regards

**Comment by 42piratas** [comment]
Hey @busernya 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still face the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repo and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers!
