### ISSUE TITLE
Akasha won't start up 

### ISSUE THREAD

**Issue by djgeorg3** [AkashaProject/Alpha#161]
Akasha is stuck at "finding piers" I tried to restart several times is still doing the same thing.

**Comment by 42piratas** [comment]
Hey @djgeorg3 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you're still facing the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
