### ISSUE TITLE
Stuck in finding peers

### ISSUE THREAD

**Issue by kopykatA** [AkashaProject/Alpha#17]
I have windows 10 Enterprise,
i tried installing AKASHA bot from exe and zip versions. Dapp wouldnt get passed the "finding peers" step.
I have chosen the express setup, both geth and ipfs icon were red.
I downloaded manually geth and ipfs and put it in my Roaming/Akasha folder. Still nothing.
Any help would be appreciated.
Thank you

**Comment by mathiasluethi** [comment]
Same issue on standard Windows 10, both exe and zip versions stuck on finding peers.

**Comment by rkoellges** [comment]
Same issue on macOS 10.12.2. during express setup. I'm stuck.

**Comment by scottc** [comment]
I was stuck with finding peers, syncing the hw clock fixed the issue for me:
https://github.com/AkashaProject/Alpha/issues/33

**Comment by rkoellges** [comment]
@scottc Thanks for the hint re hw clock. 

Synced hw clock, but still stuck.

**Comment by HuhnSolo** [comment]
Exactly the same here with both express and advanced setup. Downloaded geth and ipfs but both services don't start when I start Akasha. Mac OSX 10.11.6

**Comment by SeverS** [comment]
Hi everyone and welcome to AKASHA
Did you get any logs/errors in any service modal? Click on ethereum or ipfs icon and navigate to logs tab
Also can you confirm that both icons have red borders?

Thanks

**Comment by HuhnSolo** [comment]
@SeverS No logs/errors in both geth and ipfs, just empty. both icons are red

**Comment by davidak** [comment]
Same on OS X 10.10.5 (14F2109).

**Comment by luciano-fiandesio** [comment]
Stuck on "Finding Peers" as well (OSX 10.13.3)

Logs in ethereum and ipfs are present and the look ok (no errors)

GETH

    connection to ipc Established!

IPFS

    Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080 Daemon is ready

**Comment by 42piratas** [comment]
Hey all!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
