### ISSUE TITLE
Add field to sort following/followers tabs

### ISSUE THREAD

**Issue by ghost** [AkashaProject/Alpha#22]
Will definetly end up necessary for the Everyone Is Here bot.

**Comment by 42piratas** [comment]
Hey @anemones 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you still have any feedback based on the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
