### ISSUE TITLE
Have "add entry" button on current stream screen

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#23]
Going trough "my entries" -> "add entry" is suboptimal - most other social media allow directly adding new content from current screen

**Comment by 42piratas** [comment]
Hey @mcgravier 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
