### ISSUE TITLE
Add upvotes/downvotes to comments.

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#24]
It's not uncommon on social media that discussion below entry, is often more interesting then entry itself, so upvote/downvote mechanism should be applied as well

**Comment by 42piratas** [comment]
Hey @mcgravier 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
