### ISSUE TITLE
Tag registration UX

### ISSUE THREAD

**Issue by kumavis** [AkashaProject/Alpha#29]
Should be able to just roll the tag registering into the post submission process to make it seamless

**Comment by MihaiAlisie** [comment]
First of all let me say that we are all in agreement that this would make a better User Experience. But, at the same time, we should remember that as the network grows most of the used tags will already be in existence...so to an extent this is a problem that will be more encountered in the early days than when we get to a decent user base.

On the technical side we see these potential issues in your proposal:

* The user has enough to publish just one of the multiple tags and then remains without gas/AETH before completing the publishing
* The user closes/drops connection before the publishing transaction can be sent (you need to publish first the new tags, in order to attach them to what you're about to publish - that's *at least* 2 blocks (~30 seconds)
* Probably many other ways which we can't think of right now :)

Now, we're definitely going to polish the UX in this section because it is quite central to AKASHA as a whole but most likely we have to experiment with a few ideas before finding the optimal solution(s) 🤘

**Comment by JanKalin** [comment]
I also suggest having a clickable visible list of most popular tags right there in the "Publish a New Entry" form, not a drop-down list in the "Tags" entry that only appears after a few letters have been typed.

**Comment by kumavis** [comment]
Could the tag registering be part of the same tx that makes the post? Then you maintain the atomic nature of the post

**Comment by bmann** [comment]
Since tags are one of the main forms of curation and discovery, there are a TON of social impacts with how you design tags, and most especially, the defaults around them.

e.g. a "clickable list of most popular tags" in the default client will cause some of the same pile on aspects of current, centralized social networks.

There's even wacky things we could try, like "local" vs. "global" tags, where boris/my-tag could be something I register, or I could collect groups of tags together to mean the same thing. Since underneath you've got a full GUID / hash for each of these tags, and the visual / interface layer is just ONE representation, we can think about how the underlying technology can enable us to do DIFFERENT things than a "regular blogging platform".

Still thinking on something concrete and usable here, tied to why people want to put tags on things in the first place. I added (new) tags to my post so I could subscribe to those tags and see if anyone else was posting about Vancouver or Canada.

(cross-posted to AKASHA for further discussion)

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/dapp#296
