### ISSUE TITLE
Akasha'Geth  always in synchronizing

### ISSUE THREAD

**Issue by pplwjd** [AkashaProject/Alpha#32]
When I installed Akasha in my windows 8.1 64bit, my Geth always in synchronizing and cannot go through.
[log.txt](https://github.com/AkashaProject/Alpha/files/710224/log.txt)

**Comment by scottc** [comment]
Are you stuck on "Finding peers"? It could be geth hwclock issue https://github.com/AkashaProject/Alpha/issues/33

**Comment by Sigmarion** [comment]
Had the same issue. Windows 7. Tried Lite synch and Normal. Easy and Advanced settings - no result.
I had installed it on Windows 10 only.

**Comment by 42piratas** [comment]
Hey all!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
