### ISSUE TITLE
Chat freezes while getting previous entries

### ISSUE THREAD

**Issue by JanKalin** [AkashaProject/Alpha#36]
- Opened chat
- The messages section was empty
- Started writing a test message
- Avatars of the previous messages appeared
- Until the messages were loaded, the cursor remained the insertion cursor ("I"):
![clipboard01](https://cloud.githubusercontent.com/assets/18305372/22024120/2ee108ea-dcc9-11e6-937f-18d2f8ea243d.png), the keyboard was unresponsive,...

**Comment by bogdanbrezuica** [comment]
Hello and thanks for taking the time to test AKASHA and report issues!

At this moment, the chat room is an experiment to test Whisper capabilities and limits. Due to the big number of messages posted (bigger than we expected), the initial load of chat messages can be quite slow or even make AKASHA unresponsive for a few moments.

We will definitely work on improvements for the chat room in the next releases, so stay tuned!
