### ISSUE TITLE
Log In Issues

### ISSUE THREAD

**Issue by JCBrouwer** [AkashaProject/Alpha#37]
I'm successfully able to reach the log in screen, however once there I encounter 2 problems.

1) Not all identities contained in my keystore are shown. Only 1 is showing at the moment and this same one does always show upon restarting, but I think at one point there were 2 identities.

2) I cannot log into the identities that are shown as clicking them does nothing. The animation (expanding grey circle) does play but there is no pop-up to log in.

I have only used functions of the GUI itself. The only thing I can think of that might be out of the ordinary is that one of the account's first and last names were :^) :^).

I can create new identities but these do not show up in the list of identities.

I'm running on Arch Linux. I used [debtap](https://github.com/helixarch/debtap) to create the install package from the supplied .deb file.

**Comment by bogdanbrezuica** [comment]
Hello and thanks for testing AKASHA and helping out!

First of all, I need to check these things:
1) Have you tried to reload the window (Ctrl + R or View -> Reload)?
2) Have you tried to restart the application?

**Comment by JCBrouwer** [comment]
Yes, I have tried both of these things and cleared the cache.

**Comment by 42piratas** [comment]
Hey @JCBrouwer 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
