### ISSUE TITLE
Startrup sometimes attempts the first time setup , even though geth and IPFS are already setup

### ISSUE THREAD

**Issue by JanKalin** [AkashaProject/Alpha#38]
Yesterday I fooled around with Akasha, created a profile, posted a post, added a comment and exited.
Today when I started it, it displayed the "First time setup". Process Explorer didn't show geth or IPFS processes.
After a few restarts, it started working properly.

**Comment by 42piratas** [comment]
Hey @JanKalin!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
