### ISSUE TITLE
Poor image conversion

### ISSUE THREAD

**Issue by mcgravier** [AkashaProject/Alpha#39]
Images stored by Akasha tend to be larger, and far worse quality than original. 

In case of detailed, hi res images this gets worse - I got conversion from 3,8MB .jpg to  6,2MB .png, with severe downscalling. It would be far better to keep original jpg format instead converting everything to png

**Comment by 42piratas** [comment]
Hey @mcgravier! 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
