### ISSUE TITLE
Start menu shortcut not being created on Windows

### ISSUE THREAD

**Issue by robsonsobral** [AkashaProject/Alpha#51]
Hi!

Installing on `C:\Program files\` results on the Start Menu not being created.

Running Akasha 0.30 on Windows 10.

Thanks.

**Comment by SeverS** [comment]
Hello @robsonsobral,
Did you used installer version (.exe) or zip version?  It is normal for zip version to not create shortcuts. 

Thanks

**Comment by robsonsobral** [comment]
The `.exe`, of course.

**Comment by 42piratas** [comment]
hey @robsonsobral 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
