### ISSUE TITLE
Akasha and geth --light?

### ISSUE THREAD

**Issue by drandreaskrueger** [AkashaProject/Alpha#56]
I do not have enough diskspace for the whole ETH chain, but I want to try Akasha.

Does it also work with `geth --light` ?  Or with parity?

I have synced Mist with `electron . --mode wallet --node-light` and the chaindata is in `/home/username/.ethereum/geth/lightchaindata`. 

How to get Akasha running now?

**Comment by ColinLeath** [comment]
what are the disk space requirements? I'd like to install it too, but am afraid I won't have room. Thanks-

**Comment by ColinLeath** [comment]
It's using geth --light I'm pretty sure. I just installed on my chromebook running galliumOS. Here's the space used:
```
:~/.ethereum$ du -h akasha-alpha/
4.4M	akasha-alpha/geth/nodes
186M	akasha-alpha/geth/chaindata
190M	akasha-alpha/geth
4.0K	akasha-alpha/keystore
190M	akasha-alpha/

```

**Comment by MihaiAlisie** [comment]
Hello @drandreaskrueger @ColinLeath,

We're currently using a private network and you need (very) advanced config skills to get it running on your own. If you want use AKASHA during alpha and avoid unpleasant scenarios, **it is highly recommended to use "Express Setup" and to not change your local Geth settings**. Also it is recommended to close Mist meanwhile using AKASHA in order to avoid potential problems for the same reason.

That being said the private chain currently used by AKASHA is quite small, with the `--fast` option it takes only ~200 Mb and ~2-5 minutes to fully sync, depending on Internet speed and HDD. The intention is to move on the main net and light clients once past the testing stages so in the future this problem will be non existent.

Not ideal, we know, but these are our growing pains :octocat:

**Comment by drandreaskrueger** [comment]
Ah, now I understand:

> We're currently using a private network

Completely misunderstood your webpages. I had thought this is running on ETH mainchain.

Perhaps you want to not store your data inside the /.ethereum/ folder, but in /.akasha/, to avoid such confusion?

> recommended to close Mist meanwhile

If you change the ports, you should not have problems coexisting with ETH mainchain nodes.

Thanks for your answer. Keep up the good work.
