### ISSUE TITLE
Should not start own IPFS deamon if one is already running.

### ISSUE THREAD

**Issue by baryluk** [AkashaProject/Alpha#59]
I have ipfs deamon already running independently of the AKASHA.

Please add an option to:

1) not start (or stop) own ipfs deamon, if requested by the user in advanced settings, to use existing external ipfs deamon. Also suggest that if the ipfs deamon is already running when starting up the akasha.

2) Beyond specifying ipfs cache location for akasha ipfs, allow setting TCP ports for akasha ipfs deamon, so both normal and akasha one can be running independently without conflicts.

I understand you bundled ipfs to make it easier for people to start working with akasha from scratch, but it is not without issues if somebody is using ipfs already for other things.

**Comment by 42piratas** [comment]
First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
