### ISSUE TITLE
Internet really slow

### ISSUE THREAD

**Issue by oyajiru** [AkashaProject/Alpha#63]
Hi and thanks for the great work done on AKASHA,

This is an issue I've read is also present with Bitcoin clients. More often than not Akasha takes up all our available bandwidth. Could there be an option to choose not to be a full node? Maybe at a penalty of having to wait in line when uploading to the network.

**Comment by 42piratas** [comment]
Hey @oyajiru!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:

**Comment by oyajiru** [comment]
Thanks and no worries. I'm on the beta and searching for bugs. I'll report
anything new in the appropriate channels.
