### ISSUE TITLE
Error while trying to post an article - MACOS

### ISSUE THREAD

**Issue by theghost1980** [AkashaProject/Alpha#65]
Hello there. I have been trying to post an article, using the app under MACOS and I don't get any error message but at the same time I'm no able to publish that article, so my question is: Is there a maximum capacity for each post? I will post a screen shot. It's a regular article with 1 image in it and around 200 words.

<img width="724" alt="screen shot 2017-02-06 at 13 20 49" src="https://cloud.githubusercontent.com/assets/24734575/22648718/cb81681a-ec6f-11e6-8a4f-4df08bb42309.png">

**Comment by bmann** [comment]
Same issue on OSX. Hitting "Save" or "Publish" both do nothing. I can't see anywhere where I can check logs or errors.

Have tried with and without images. Have tried with and without "(" character in title.

Happy to troubleshoot, let me know what I can look at.

**Comment by SeverS** [comment]
Hello, 
Did you tried to copy/paste a text from anywhere or it was written by you? We have an issue with the text editor that does not allow links to be copy/pasted. This issue will be solved in the next release.

**Comment by bmann** [comment]
@SeverS thanks for the tip. Got a first post published after typing the whole thing in. This item can be closed

**Comment by bmann** [comment]
I can't edit the title, but I have fully verified that it is not about cut and pasting, it is about adding links. If you use the editor to add even one link, then it refuses to save or publish. I published a post with two images and no links, saving often, and it worked fine.

**Comment by sillygwailo** [comment]
Same here. I pasted in nothing, and handcrafted the URLs, and I can't save or publish.

**Comment by bmann** [comment]
Richard -- no links work, copy paste or original.

**Comment by 42piratas** [comment]
Hey all!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
