### ISSUE TITLE
Synchronizing stop or do nothing 

### ISSUE THREAD

**Issue by miguelmarques70** [AkashaProject/Alpha#76]
Hello! I tried with the version 0.3 and now with 0.5 and Synchronizing doesn't do nothing for the past 40mn. View detais also shows nothing. I'm on windows 7 environment and tried do disconnect the anti-virus but it's the same. Any ideas? Thanks

**Comment by miguelmarques70** [comment]
Yes, more than 90 minutes passed, I do reload but synchronizing doesn't do nothing.

**Comment by 42piratas** [comment]
Hey @miguelmarques70!
 
First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
