### ISSUE TITLE
Minor UX bug with attaching image to entry

### ISSUE THREAD

**Issue by rowanthorpe** [AkashaProject/Alpha#78]
When I tried attaching a GIF to a post just now, I typed the title, clicked in the content section and started typing, then wanted to attach the image and couldn't find anywhere/way to do so, and of course drag-and-drop didn't work. In the end with help from users on the slack channel I found that the "plus-in-a-circle" symbol which needs to be clicked for uploading an image only appears when the cursor is inside the text-entry box, and on an empty line. In the end I got it to work, but obviously that was non-intuitive, and there should be a more obvious signposting of how to do it, and not only under the specific condition mentioned above. I presume it is the same for all interfaces, but note that I am using the Linux interface, in case it makes a difference.

**Comment by 42piratas** [comment]
Hey again @rowanthorpe 

Closing this one as well because, as I mentioned before, the repo will be archived. If you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thanks again! 

Cheers! :pray::metal:
