### ISSUE TITLE
No instructions to backup identity

### ISSUE THREAD

**Issue by come-maiz** [AkashaProject/Alpha#83]
After finishing the account creation, I get a suggestion to backup my ID, but this suggestion comes with no instructions.

I found the instructions here:
https://github.com/AkashaProject/Alpha/wiki/FAQ#how-can-i-backup-my-identity-andor-port-it-to-another-machine

So it would be good to at least put a link to that page.

![ekrankopio de 2017-03-07 13-08-09](https://cloud.githubusercontent.com/assets/617831/23673331/830cb38a-0337-11e7-88ad-6346754c5eab.png)

**Comment by 42piratas** [comment]
Hey again @elopio 

As for the other issue, I'm closing this one because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you again for getting in touch! 

Cheers! :pray::metal:
