### ISSUE TITLE
When the window is smaller, there is not enough padding between the letter and the sections

### ISSUE THREAD

**Issue by come-maiz** [AkashaProject/Alpha#86]
I made the window small while redacting a new post, and in many places the letters appear to close to other sections, or even on top of gray areas.

![ekrankopio de 2017-03-07 13-34-35](https://cloud.githubusercontent.com/assets/617831/23674309/1a5c5788-033b-11e7-88d0-d4b2bc28acb9.png)

**Comment by 42piratas** [comment]
Hey @elopio!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
