### ISSUE TITLE
Linux: Confusion while posting entries with tags

### ISSUE THREAD

**Issue by Bevor** [AkashaProject/Alpha#91]
I want to submit a draft by clicking "Publish". Then it wants me to add a tag. I try to add a tag from the upper right corner from the "stream" view (e.g. akasha, where I also subscribed to). Instead I get proposals inside the text view like "akasha-explained", akasha-feature", "akashadev",...
If I even try to submit with "akasha", I get an error hint that I "must add at least 1 valid tag". Then I figured out that I have to press enter to confirm the tag first. This is confusing.
Solution: Tags should be auto-confirmed when the user does not confirm it manually.

**Comment by 42piratas** [comment]
Hey @Bevor!

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
