### ISSUE TITLE
Linux: Draft has wrong version and Update not working

### ISSUE THREAD

**Issue by Bevor** [AkashaProject/Alpha#93]
I have a 'listed' entry in "version 1". 
I click the pencil icon to edit it.
I change the text to "version 2". 
-> SAVE -> "Draft successfully saved"
I go to "my entries". -> DRAFTS
=> Draft has still version 1 and not version 2.
I go back to the draft. 
I click UPDATE
=> The next view called "Publish a new version" still shows "version 1".
-> I update the text there to "version 2".
-> I click UPDATE
=> Nothing happens. UPDATE button not working

**Comment by 42piratas** [comment]
Hey again @Bevor!

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

Thank you again for getting in touch!

Cheers! :pray::metal:
