### ISSUE TITLE
Unable to publish photos

### ISSUE THREAD

**Issue by webster** [AkashaProject/Alpha#95]
I've attempted a few times to publish a post with one or more high-resolution photos, and after clicking 'Publish' nothing seems to happen. It says 'Saving draft...' in the top left corner, but there are no status updates, there doesn't seem to be an increase in bandwidth consumption consistent with sending the image(s), and even if you cancel, the publish experience is frozen-out and non-working until you restart Akasha.

I've seen images in other Akasha posts, so I'm wondering if there's a filesize limit or recommendation? I was trying to include images that were in the 10-15MB range. If there's a filesize limit, that should be disclosed to users, but also, images should be scaled if necessary.

It would be useful to have some sort of 'console' to see what is really happening in the background during the publication process. Thanks!

macOS 10.12.2 - AKASHA 0.5.2

**Comment by ryivhnn** [comment]
I need a "me too" button :) Had pretty much exactly the same thing happen on a SP4 running Win10 and a Manjaro box.

Only other difference is my images are smaller (from under 1Mb to 4Mb).

**Comment by vistun** [comment]
I'm attempting to post an image of exactly 500 kb, received a 'failed to save draft' toast, but 'saving draft' persists.

**Comment by 42piratas** [comment]
Hey @webster @ryivhnn @vistun!


First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
