### ISSUE TITLE
Difference between 'listed' and 'unlisted' entries not explained

### ISSUE THREAD

**Issue by webster** [AkashaProject/Alpha#96]
Under 'My entries' there is a tab for Drafts, Listed, and Unlisted. There's no explanation about what listed versus unlisted means, what would cause an entry to be unlisted, or whether that's a configuration option on an account or per-entry level.

AKASHA v0.5.2 - macOS 10.12.2

<img width="192" alt="screen shot 2017-03-20 at 11 26 58 am" src="https://cloud.githubusercontent.com/assets/166752/24110017/55bfb700-0d60-11e7-9beb-f42778ea1ac6.png">

**Comment by 42piratas** [comment]
Hey @webster 

First, I'm sorry for the late reply. 

Have you tried the latest beta version? https://beta.akasha.world

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
