### ISSUE TITLE
libusb not found - geth does not start

### ISSUE THREAD

**Issue by Dunkhan** [AkashaProject/Alpha#97]
Windows 7

This issue was mentioned in issue #60. @SeverS mentioned that he would help if a new issue was posted.
This is a fresh install of 0.5.2
At first it had issues with ipfs. This may have been because I already had an ipfs daemon running. After I stopped the daemon and restarted Akasha I get the current issue.

Thanks in advance

Log: 
13:59:49
geth:spawn:close: 1

error
13:59:49
geth: exited with code: 1

info
13:59:49
I0324 13:59:49.799325 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default I0324 13:59:49.799325 ethdb/database.go:83] Allotted 512MB cache and 1024 file handles to C:\Users\me\AppData\Roaming\Ethereum\akasha-alpha\geth\chaindata

info
13:59:49
I0324 13:59:49.798325 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5]

error
13:59:49
Command failed: "C:\Users\me\AppData\Roaming\AKASHA\geth.exe" --datadir="C:\Users\me\AppData\Roaming\Ethereum\akasha-alpha" init "C:\Users\me\AppData\Roaming\AKASHA\akasha.alpha.json" I0324 13:59:49.559311 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5] I0324 13:59:49.559311 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default I0324 13:59:49.559311 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to C:\Users\me\AppData\Roaming\Ethereum\akasha-alpha\geth\chaindata

**Comment by 42piratas** [comment]
Hey @Dunkhan 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you have any feedback related to the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and we'll get back to you.

And thank you very much for getting in touch! We appreciate your contribution. 

Cheers! :pray::metal:
